<?php
/**
 * ConfiguratorApiTest
 * PHP version 5
 *
 * @category Class
 * @package  WheelSizeApiClient\Configurator
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wheel Configurator API
 *
 * Wheel Configurator API is a part of Wheel Fitment API v2.  The Wheel Configurator API is a tool that allows users to visualize wheel  and tire upgrades on vehicles. It can be integrated into any website   or application to enhance the customer shopping experience by allowing them to visualize   their vehicle with different wheel options,    which can lead to increased sales and customer satisfaction.       **NOTE:** A _Configurator Template_ is a vehicle-specific image prepared  for custom rim installation via a URL or file upload.       [Demo](https://api-demo.wheel-size.com/),  [FAQs](https://api-demo.wheel-size.com/),
 *
 * OpenAPI spec version: v2
 * Contact: info@wheel-size.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace WheelSizeApiClient\Configurator;

use WheelSizeApiClient\Configurator\Configuration;
use WheelSizeApiClient\Configurator\ApiException;
use WheelSizeApiClient\Configurator\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConfiguratorApiTest Class Doc Comment
 *
 * @category Class
 * @package  WheelSizeApiClient\Configurator
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfiguratorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for configuratorTemplate
     *
     * Get detailed info about selected Configurator Template ID.
     *
     */
    public function testConfiguratorTemplate()
    {
    }

    /**
     * Test case for configuratorTemplateColors
     *
     * Get A List of OE colors with names for a specific Configurator Template ID.
     *
     */
    public function testConfiguratorTemplateColors()
    {
    }

    /**
     * Test case for configuratorTemplateRimFit
     *
     * Generate an image of the Configurator Template (vehicle) with the specified rim.
     *
     */
    public function testConfiguratorTemplateRimFit()
    {
    }

    /**
     * Test case for configuratorTemplates
     *
     * Get A List of Configurator Templates.
     *
     */
    public function testConfiguratorTemplates()
    {
    }

    /**
     * Test case for generations
     *
     * Get A List of Car Generations.
     *
     */
    public function testGenerations()
    {
    }

    /**
     * Test case for makes
     *
     * Get A List of Makes.
     *
     */
    public function testMakes()
    {
    }

    /**
     * Test case for models
     *
     * Get A List of Models via Different Filters.
     *
     */
    public function testModels()
    {
    }

    /**
     * Test case for years
     *
     * Get A List of Years.
     *
     */
    public function testYears()
    {
    }
}
